name: mobile_app_standard
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

flavors:
    dev:
      app:
        name: "mobile_app_standard Dev"
        identifier: com.example.mobile_app.dev
      android:
        applicationId: com.example.mobile_app.dev
    prod:
      app:
        name: "mobile_app_standard"
        identifier: com.example.mobile_app
      android:
        applicationId: com.example.mobile_app

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drift: ^2.23.1
  drift_flutter: ^0.1.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  intl: ^0.19.0
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.2.1
  auto_route: ^7.2.0
  flutter_tailwind_colors: ^0.0.3
  toastification: ^3.0.2
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  skeletonizer: ^1.4.3
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.23.1
  build_runner: ^2.4.14
  auto_route_generator: ^7.1.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - .env
